import { Montserrat } from "next/font/google";

import "./globals.css";
import Nav from "@/components/Nav";

export const dynamic = "force-dynamic";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont.className}>
      <div className="bg-[#FFF8EE]">
      <Nav/>
      </div>
        {children}
      </body>
    </html>
  );
}
